### PR TITLE
[WIP] Feature add runSignature function

### PR DESCRIPTION
**Pull request by st-duymai**
This pull request adds the ability to run signatures in Flutter TFLite.

List of functions added and their testing status:

- [x] getSignatureInputCount(String signatureKey)
- [x] getSignatureOutputCount(String signatureKey)
- [x] getSignatureInputName(String signatureKey, int index)
- [x] getSignatureOutputName(String signatureKey, int index)
- [x] getSignatureInputTensorShape(String signatureKey, String inputName)
- [x] getSignatureOutputTensorShape(String signatureKey, String outputName)
- [x] runSignature(Map<String, Object> inputs, Map<String, Object> outputs, String signatureKey)
- [x] deleteSignatureRunner(String signatureKey)

### CODE REVIEW

**Comment by CaptainDario** [comment]
@st-duymai are you still working on this? It would be an awesome addition!

**Comment by st-duymai** [comment]
> @st-duymai are you still working on this? It would be an awesome addition!

I'm still working on it. I'm doing it with the MoviNet sample. When I finish it, it would be great if you could help me review it.

**Comment by michaeltys** [comment]
Hi @st-duymai , thanks for your contribution. I was testing the movinet sample and found that inference takes 1 - 2 seconds to complete for a single frame. I checked with multiple frame dimensions (from 20*20 to 1000*1000) and the result is the same. Do you see a possible way to improve the performance here?

I took android implementation as a reference, the inference there takes 20-50 milliseconds on the same data even using Flutter Chanel for native code integration

**Comment by michaeltys** [comment]
> In my experience, TF Lite flutter is close to the native c performance.
> 
> Are you sure that you only measure the inference latency? Not the frame decoding from the camera?

Yes, I measured just the inference time. Frame decoding takes really little in comparison to the inference in this case

**Comment by CaptainDario** [comment]
@michaeltys, did you try running it in the native tf lite Benchmark app?

Also, could you provide a link to the model?

**Comment by st-duymai** [comment]
@michaeltys Yes, I know this issue. The reason is when I use isolate, I can't remain all tensors and signatures during each inference.

**Comment by st-duymai** [comment]
I am closing this pull request as I will no longer be using this GitHub account. I may create a new pull request later.

**Pull request closed without merging**
