### PR TITLE
[Fixes] Minor doc fixes as well as removed Metal delegate for iOS

### PR DESCRIPTION
**Pull request by VadymPinchuk**
Minor fixes for the documentation, as well as review for the comments from @PaulTR in [PR #107](https://github.com/tensorflow/flutter-tflite/pull/107#issuecomment-1658878679)

@PaulTR 
- Metal delegate removed.  
- There is nothing to do with imageFormatGroup, it is related to CameraController, and default value set for each platform:  bgra8888 for iOS and yuv420 for Android
- Orientation - not fixed.
- Minor fixes in the docs, typos

### CODE REVIEW

**Comment by VadymPinchuk** [comment]
What I have noticed, Android delegate also could be removed, at least for pixel it works perfectly, cant say anything about other devices.

**Comment by gregorscholz** [comment]
Xiaomi Redmi 9 also works without delegate, and maybe add the path for the app to the `.vscode-workspace` file.

Also, i dont know if you remember, but I think we met at fluttercon on wednesday morning before it even started. I was the one with the long hair 😅

**Comment by PaulTR** [comment]
> Also, i dont know if you remember, but I think we met at fluttercon on wednesday morning before it even started. I was the one with the long hair 😅

Nice! Are you going to be at the Flutter Firebase Festival in Prague next month as well?

**Comment by gregorscholz** [comment]
@PaulTR unfortunately not

**Comment by VadymPinchuk** [comment]
@PaulTR  I will be there, but I will land Prague around 11 AM, and will be there around lunch time. So can hangout later, after your talk

**Pull request merged**
