### PR TITLE
fix compatibility with latest 'stable' flutter build + bump min sdk to 3.3.0

### PR DESCRIPTION
**Pull request by ptgms**
The latest Flutter Version broke this package (see #232). This PR restores functionality with the downside of bumping the minimum dart sdk to 3.3.0.

If that is too harsh and there is a better solution, feel free to decline, I won't mind :)

### CODE REVIEW

**Comment by PaulTR** [comment]
Let me check to see how many devs are using 3.3.0 or later, but if it's a decent number then this seems reasonable.

**Comment by PaulTR** [comment]
Also looks like this just needs a quick format check

**Comment by PaulTR** [comment]
Alright if you can just run the format command (I want to say it was ` dart format --output=none --set-exit-if-changed .`) this should be good to go - upping the version seems like a good plan on my side.

**Comment by ptgms** [comment]
done :)

**Comment by PaulTR** [comment]
This one might take a minute to get into the full package. Fighting ffigen and building with error messages around `error - lib/src/bindings/tensorflow_lite_bindings_generated.dart:2060:7 - The type 'TfLiteModel' must be 'base', 'final' or 'sealed' because the supertype 'Opaque' is 'base'. - subtype_of_base_or_final_is_not_base_final_or_sealed` - figuring out what needs to be changed to pass that via `flutter pub run ffigen --config ffigen_tensorflow_lite.yaml`

**Comment by andresgd7** [comment]
dude i love u

**Comment by ptgms** [comment]
@PaulTR ill try and take a look if i can figure something out :) 
lets get this fixed so our developer friends can start using this package again :)

**Comment by efisiobova** [comment]
Not working

`/AppData/Local/Pub/Cache/hosted/pub.dev/tflite_flutter-0.10.4/lib/src/tensor.dart:58:12: Error: The method 'UnmodifiableUint8ListView' isn't defined for the class 'Tensor'.
 - 'Tensor' is from 'package:tflite_flutter/src/tensor.dart' ('/C:/Users/efisi/AppData/Local/Pub/Cache/hosted/pub.dev/tflite_flutter-0.10.4/lib/src/tensor.dart').
Try correcting the name to the name of an existing method, or defining a method named 'UnmodifiableUint8ListView'.
    return UnmodifiableUint8ListView(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.`

**Comment by SametSahin10** [comment]
Will there be a new version that makes this fix available to everyone?

**Pull request merged**
