### PR TITLE
Feature - Implement pose estimation Posenet

### PR DESCRIPTION
**Pull request by st-duymai**

### CODE REVIEW

**Comment by PaulTR** [comment]
Looks like some of the points may be incorrectly connected, and scaling might be off?

Screenshot_20231016-094456

**Comment by PaulTR** [comment]
In case it helps, there was another PR not too long ago that the author closed due to it taking a moment to get to PR reviews that might be useful https://github.com/tensorflow/flutter-tflite/tree/pose_detection_olololoe

**Comment by st-duymai** [comment]
> Looks like some of the points may be incorrectly connected, and scaling might be off?
> 
> Screenshot_20231016-094456

I apologize for the mistake. I used the wrong aspect ratio when refactoring the code. I have updated the code and it now works correctly on Android, but it is still slightly incorrect on iOS. I am working on fixing it, but it may take some time. Thank you for your patience.

**Comment by PaulTR** [comment]
Cool sounds good. Thanks!

**Comment by st-duymai** [comment]
Hi Mr @PaulTR , I fixed the scale issue on Android and iOS. Can you please take a look? Thanks!

**Comment by PaulTR** [comment]
Alright looks good on iPhone, iPad, and an Android phone. Thanks Duy!

**Pull request merged**
