### PR TITLE
adding an object detection example application

### PR DESCRIPTION
**Pull request by gregorscholz**
This is a simple application for an object detection application following [this](https://www.tensorflow.org/lite/examples/object_detection/overview) tutorial.
If you have any suggestions, please let me know!

---
This is a followup to [this](https://github.com/tensorflow/flutter-tflite/pull/69) closed pr.

### CODE REVIEW

**Comment by PaulTR** [comment]
I'll check/test this on Tuesday when I'm back at my work computer :) Thanks!

**Comment by PaulTR** [comment]
Has the example app on iOS been verified? It works as expected on Android, but crashes when trying to start the camera or open the gallery on iOS.

**Comment by PaulTR** [comment]
Found the issue - you'll just need to update info.plist to include:

<key>NSCameraUsageDescription</key>
<string>Access camera</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>Library</string>

**Comment by PaulTR** [comment]
Alright other than that one small fix for running on iOS I think this looks golden. Thanks!

**Comment by gregorscholz** [comment]
Thank you for your feedback! Tbh, i completely forgot to test this on ios. Here is the fix.

image

**Comment by gregorscholz** [comment]
Nevermind, pipeline fails...
Can someone maybe help me here?

If i run `dart format .` i get `Formatted 26 files (0 changed) in 0.90 seconds.`. What exactly is wrong here?

**Pull request merged**
